name: commerce_models
description: Models for e-commerce projects.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  intl: ^0.16.1
  cloud_firestore_platform_interface: ^2.0.0-dev.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: